apiVersion: batch/v1
kind: Job
metadata:
  name: job-debug-dev
  namespace: ns-devops-dev
spec:
  template:
    metadata:
      labels: 
        sidecar.istio.io/inject: "false"
    spec:
      # tolerations:
      # - key: "dedicated"
      #   operator: "Equal"
      #   value: "critical"
      #   effect: "NoSchedule"
      # nodeSelector:
      #   dedicated: critical
      containers:
        - name: cn-debug-dev
          image: nicolaka/netshoot
          command: ["sleep",  "infinity"]
          securityContext:
            privileged: true
            capabilities:
              add: 
              - NET_ADMIN
              - NET_RAW
              - SYS_TIME
      hostNetwork: true
      restartPolicy: Never
  backoffLimit: 1